apiVersion: v1
kind: Service
metadata:
  name: planilla-service
  labels:
    app: planilla-service
spec:
  selector:
    app: planilla-deployment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer