apiVersion: v1
kind: Service
metadata:
  name: proveedores-service
  labels:
    app: proveedores-service
spec:
  selector:
    app: proveedores-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer