apiVersion: v1
kind: Service
metadata:
  name: valores-service
  labels:
    app: valores-service
spec:
  selector:
    app: valores-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer