server:
  port: 8383
spring:
  application:
    name: planillaGenerate
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}