INSERT INTO proveedores (categoria, code, nombre, retencion) VALUES ('D', '1000', 'nombre0', 0);
INSERT INTO proveedores (categoria, code, nombre, retencion) VALUES ('B', '1001', 'lechera1', 0);
INSERT INTO proveedores (categoria, code, nombre, retencion) VALUES ('C', '1002', 'nombre2', 0);
INSERT INTO proveedores (categoria, code, nombre, retencion) VALUES ('C', '1003', 'nombre3', 0);
INSERT INTO proveedores (categoria, code, nombre, retencion) VALUES ('B', '1004', 'nombre4', 1);
INSERT INTO proveedores (categoria, code, nombre, retencion) VALUES ('A', '1005', 'nombre5', 0);
INSERT INTO proveedores (categoria, code, nombre, retencion) VALUES ('C', '1006', 'nombre6', 1);
INSERT INTO proveedores (categoria, code, nombre, retencion) VALUES ('D', '1007', 'nombre7', 1);
INSERT INTO proveedores (categoria, code, nombre, retencion) VALUES ('A', '1008', 'nombre8', 1);
